blank_issues_enabled: false
contact_links:
  - name: 🔎 Search existing issues
    url: https://github.com/ConsoleFlow-Group/ConsoleFlow-mobile/issues
    about: Please check whether your issue already exists before opening a new one.
